// Offline radio station data — curated list of stable streams
// Used as fallback when radio-browser.info API is unavailable
import type {Station} from '../../types/station.types.ts';

export const OFFLINE_STATIONS: Station[] = [
	// === Poland ===
	{
		id: 'rmf-fm',
		name: 'RMF FM',
		streamUrl: 'https://rs8-krk2-cyfronet.rmfstream.pl/RMFFM48',
		country: 'Poland',
		language: 'polish',
		genre: 'Pop',
		tags: ['polish', 'pop', 'hits'],
		homepage: 'https://www.rmf.fm',
	},
	{
		id: 'radio-zet',
		name: 'Radio ZET',
		streamUrl: 'https://zt.cdn.eurozet.pl/ZETMP3.mp3',
		country: 'Poland',
		language: 'polish',
		genre: 'Pop',
		tags: ['polish', 'pop', 'news'],
		homepage: 'https://www.radiozet.pl',
	},
	{
		id: 'polskie-radio-1',
		name: 'Polskie Radio Program I',
		streamUrl: 'https://stream3.polskieradio.pl:8050/',
		country: 'Poland',
		language: 'polish',
		genre: 'Public Radio',
		tags: ['polish', 'public', 'news', 'culture'],
		homepage: 'https://www.polskieradio.pl/1/',
	},
	{
		id: 'polskie-radio-3',
		name: 'Polskie Radio Program III (Trójka)',
		streamUrl: 'https://stream3.polskieradio.pl:8070/',
		country: 'Poland',
		language: 'polish',
		genre: 'Rock / Alternative',
		tags: ['polish', 'rock', 'alternative', 'culture'],
		homepage: 'https://www.polskieradio.pl/3/',
	},
	{
		id: 'radio-eska',
		name: 'Radio Eska',
		streamUrl: 'https://www.eskago.pl/radio/eska',
		country: 'Poland',
		language: 'polish',
		genre: 'Pop / Hits',
		tags: ['polish', 'pop', 'hits', 'top40'],
		homepage: 'https://www.eska.pl',
	},
	{
		id: 'eska-rock',
		name: 'Eska Rock',
		streamUrl: 'https://www.eskago.pl/radio/eska-rock',
		country: 'Poland',
		language: 'polish',
		genre: 'Rock',
		tags: ['polish', 'rock', 'alternative'],
		homepage: 'https://www.eskago.pl/radio/eska-rock',
	},
	{
		id: 'radio-vox-fm',
		name: 'Radio VOX FM',
		streamUrl: 'https://www.eskago.pl/radio/vox-fm',
		country: 'Poland',
		language: 'polish',
		genre: 'Pop / Hits',
		tags: ['polish', 'pop', 'hits'],
		homepage: 'https://www.voxfm.pl',
	},
	{
		id: 'radio-zlote-przeboje',
		name: 'Radio Złote Przeboje',
		streamUrl: 'https://www.eskago.pl/radio/zlote-przeboje',
		country: 'Poland',
		language: 'polish',
		genre: 'Oldies / Classic Hits',
		tags: ['polish', 'oldies', 'classic', 'hits'],
		homepage: 'https://www.zloteprzeboje.pl',
	},
	{
		id: 'radio-90',
		name: 'Radio 90',
		streamUrl: 'https://www.eskago.pl/radio/90',
		country: 'Poland',
		language: 'polish',
		genre: 'Oldies / 90s',
		tags: ['polish', '90s', 'oldies'],
		homepage: 'https://www.radio90.pl',
	},
	{
		id: 'antyradio',
		name: 'Antyradio',
		streamUrl: 'https://www.eskago.pl/radio/antyradio',
		country: 'Poland',
		language: 'polish',
		genre: 'Rock',
		tags: ['polish', 'rock', 'metal', 'alternative'],
		homepage: 'https://www.antyradio.pl',
	},
	{
		id: 'radio-rmf-maxx',
		name: 'RMF MAXX',
		streamUrl: 'https://rs9-krk2-cyfronet.rmfstream.pl/RMFMAXX48',
		country: 'Poland',
		language: 'polish',
		genre: 'Pop / Dance',
		tags: ['polish', 'pop', 'dance', 'hits'],
		homepage: 'https://www.rmfmaxx.pl',
	},
	{
		id: 'rmf-classic',
		name: 'RMF Classic',
		streamUrl: 'https://rs9-krk2-cyfronet.rmfstream.pl/RMFCLASSIC48',
		country: 'Poland',
		language: 'polish',
		genre: 'Classical',
		tags: ['polish', 'classical', 'relax'],
		homepage: 'https://www.rmfclassic.pl',
	},
	{
		id: 'tok-fm',
		name: 'TOK FM',
		streamUrl: 'https://stream3.polskieradio.pl:8090/',
		country: 'Poland',
		language: 'polish',
		genre: 'News / Talk',
		tags: ['polish', 'news', 'talk', 'public'],
		homepage: 'https://www.tokfm.pl',
	},
	{
		id: 'radio-rdk',
		name: 'Radio Dla Ciebie (RDC)',
		streamUrl: 'https://stream3.polskieradio.pl:8228/',
		country: 'Poland',
		language: 'polish',
		genre: 'Public Radio',
		tags: ['polish', 'public', 'news', 'regional'],
		homepage: 'https://www.rdc.pl',
	},
	{
		id: 'polskie-radio-2',
		name: 'Polskie Radio Program II (Dwójka)',
		streamUrl: 'https://stream3.polskieradio.pl:8060/',
		country: 'Poland',
		language: 'polish',
		genre: 'Classical / Culture',
		tags: ['polish', 'classical', 'culture', 'jazz'],
		homepage: 'https://www.polskieradio.pl/2/',
	},
	{
		id: 'polskie-radio-4',
		name: 'Polskie Radio Program IV (Czwórka)',
		streamUrl: 'https://stream3.polskieradio.pl:8080/',
		country: 'Poland',
		language: 'polish',
		genre: 'Youth / Alternative',
		tags: ['polish', 'youth', 'alternative', 'pop'],
		homepage: 'https://www.polskieradio.pl/4/',
	},
	{
		id: 'radio-ostrowiec',
		name: 'Radio Ostrowiec',
		streamUrl: 'https://stream.radioostrowiec.pl:8443/stream.mp3',
		country: 'Poland',
		language: 'polish',
		genre: 'Local',
		tags: ['polish', 'local', 'regional'],
		homepage: 'https://radioostrowiec.pl',
	},

	// === International ===
	{
		id: 'bbc-radio-1',
		name: 'BBC Radio 1',
		streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
		country: 'United Kingdom',
		language: 'english',
		genre: 'Pop / Top 40',
		tags: ['uk', 'bbc', 'pop', 'top40', 'hits'],
		homepage: 'https://www.bbc.co.uk/radio1',
	},
	{
		id: 'bbc-radio-2',
		name: 'BBC Radio 2',
		streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two',
		country: 'United Kingdom',
		language: 'english',
		genre: 'Adult Contemporary',
		tags: ['uk', 'bbc', 'adult', 'pop', 'easy'],
		homepage: 'https://www.bbc.co.uk/radio2',
	},
	{
		id: 'bbc-radio-4',
		name: 'BBC Radio 4',
		streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm',
		country: 'United Kingdom',
		language: 'english',
		genre: 'News / Talk',
		tags: ['uk', 'bbc', 'news', 'talk', 'culture'],
		homepage: 'https://www.bbc.co.uk/radio4',
	},
	{
		id: 'npr-news',
		name: 'NPR News',
		streamUrl: 'https://npr-ice.streamguys1.com/live.mp3',
		country: 'United States',
		language: 'english',
		genre: 'News / Talk',
		tags: ['us', 'npr', 'news', 'public', 'talk'],
		homepage: 'https://www.npr.org',
	},
	{
		id: 'kexp',
		name: 'KEXP 90.3 FM',
		streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
		country: 'United States',
		language: 'english',
		genre: 'Indie / Alternative',
		tags: ['us', 'seattle', 'indie', 'alternative', 'non-profit'],
		homepage: 'https://www.kexp.org',
	},
	{
		id: 'npo-radio-1',
		name: 'NPO Radio 1',
		streamUrl: 'https://icecast.omroep.nl/radio1-bb-mp3',
		country: 'Netherlands',
		language: 'dutch',
		genre: 'News / Talk',
		tags: ['nl', 'news', 'talk', 'public'],
		homepage: 'https://www.nporadio1.nl',
	},
	{
		id: 'fip',
		name: 'FIP',
		streamUrl: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
		country: 'France',
		language: 'french',
		genre: 'Eclectic / Chill',
		tags: ['fr', 'eclectic', 'chill', 'public', 'jazz'],
		homepage: 'https://www.radiofrance.fr/fip',
	},
	{
		id: 'dlf',
		name: 'Deutschlandfunk',
		streamUrl: 'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3',
		country: 'Germany',
		language: 'german',
		genre: 'News / Talk',
		tags: ['de', 'news', 'talk', 'public', 'culture'],
		homepage: 'https://www.deutschlandfunk.de',
	},
	{
		id: 'npo-radio-2',
		name: 'NPO Radio 2',
		streamUrl: 'https://icecast.omroep.nl/radio2-bb-mp3',
		country: 'Netherlands',
		language: 'dutch',
		genre: 'Pop / Hits',
		tags: ['nl', 'pop', 'hits', 'public'],
		homepage: 'https://www.nporadio2.nl',
	},
	{
		id: 'rai-radio-1',
		name: 'Rai Radio 1',
		streamUrl: 'https://icestreaming.rai.it/1.mp3',
		country: 'Italy',
		language: 'italian',
		genre: 'News / Talk',
		tags: ['it', 'news', 'talk', 'public'],
		homepage: 'https://www.raiplayradio.it/radio1/',
	},
];

export const STATION_COUNTRIES = [
	...new Set(OFFLINE_STATIONS.map(s => s.country)),
].sort();

export const STATION_LANGUAGES = [
	...new Set(OFFLINE_STATIONS.map(s => s.language)),
].sort();
